### ISSUE TITLE
The catalog allows to have a different name for the object name and the workflow name

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/catalog#213] opened 2020-04-30 08:29 UTC
The catalog should not allow to have a different name for a workflow name and its name describe in the xml.

**Comment by ShatalovYaroslav** [comment] 2020-05-15 14:51
The issue is closed in PR: https://github.com/ow2-proactive/catalog/pull/215

**Closed by ShatalovYaroslav** 2020-05-15 14:51 UTC
